# Generated by Django 3.2 on 2023-09-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_auto_20230906_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='created',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='created',
            new_name='pub_date',
        ),
    ]
