# Generated by Django 3.2 on 2023-09-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0008_auto_20230907_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название произведения'),
        ),
    ]
