# Generated by Django 3.2 on 2023-09-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0009_alter_titles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='Рейтинг'),
        ),
    ]
