# Generated by Django 3.2 on 2023-09-06 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0010_alter_titles_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlesgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='titles.genres'),
        ),
        migrations.AlterField(
            model_name='titlesgenre',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='titles.titles'),
        ),
    ]
