# Generated by Django 3.2 on 2023-09-06 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0011_auto_20230907_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlesgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='titles.genres'),
        ),
        migrations.AlterField(
            model_name='titlesgenre',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='titles.titles'),
        ),
    ]
